### ISSUE TITLE
Remove Boost

### ISSUE THREAD

**Issue by LoganDark** [KazDragon/terminalpp#190]
Could Boost be removed from this project? As far as I can tell you only use relatively simple things like `optional`. I'd be interested in knowing if a non-Boost version is possible.

**Comment by KazDragon** [comment]
Hi LoganDark, and thanks for your interest.

I think that you're right: nearly everything, if not actually everything, that I use from Boost in this project is present in C++17.  So for the most part, you could search/replace boost/std and recompile, modulo header changes.

I haven't given it much thought myself since my own downstream projects (Paradice9, Munin) use Boost anyway.  Would a Boost-less version of Terminal++ be of significant value to you? (if so, awesome!)

**Comment by LoganDark** [comment]
> Would a Boost-less version of Terminal++ be of significant value to you?

Possibly... Can Terminal++ be used as a C++14 header-only library? C++17 is too new for repl.it (the stupid online environment my school uses)

**Comment by KazDragon** [comment]
Hmm.  Header-only isn't a design choice I would make with this.  I very much prefer to keep the implementation details and the interface separate.  If you wanted, you could fork the project and copy the source files into the header files, with minor changes (e.g. giving anonymous namespaces a name).

**Comment by LoganDark** [comment]
Header-only only means that there is a file you can `#include` that doesn't require a linking step. e.g. a file that includes the `.h` and `.cpp` files in order so you don't need to compile them separately. I'll create a separate issue for this.

**Comment by KazDragon** [comment]
I understand what header-only is.  But, as I said, it's a design decision I would not take with this library myself.  If you want to fork the library and apply that transformation, that's fine.

**Comment by LoganDark** [comment]
> I understand what header-only is

> that transformation

No, no. I'm not asking to change the library itself to be header-only. I'm asking for some file/header I can `#include` that `#include`s the rest of the library as well.

For example, my boilerplate thing uses this.

![image](https://user-images.githubusercontent.com/4723091/49800345-1e977280-fcfc-11e8-8273-3642235ec8ed.png)

Couldn't you do the same with the `.cpp` files in order to create a "header-only" (in quotes) file?

**Comment by KazDragon** [comment]
I'm struggling to understand in what way that would benefit anyone.

**Comment by LoganDark** [comment]
It would benefit people without a linker.

Online environments like repl.it only support compiling one program.

**Comment by KazDragon** [comment]
Ugh, ok.
So I've had a look at repl.it and it's indeed a highly restrictive platform.  It doesn't even let you set an include path, which means that I would also have to change all of my includes to be relative to each other rather than relative to the include root (e.g. #include "../detail/foo.hpp" instead of #include "telnetpp/detail/foo.hpp" and that was another explicit design decision.

And then, of course, there is the issue of whether the output will even be rendered correctly in that terminal-like window.

I really don't think I could support this use case, if only because I have no way of automatically testing that it stays in tact.

I think the best course of action for you if you still want to pursue this course is to copy the .hpp and .cpp files from the library into your project flat.  That is, without any subdirectories.  Then, change all of the #includes to be flat as well.

Of course, that leaves the Boost dependency.  You could potentially do this as well, just for Variant and Optional, which I hope don't require you to drag in too much of Boost (possibly just Boost.Config).

That's quite the work for a school assignment. :-/

**Comment by LoganDark** [comment]
> And then, of course, there is the issue of whether the output will even be rendered correctly in that terminal-like window.

The student console (the stupid line-buffered mess) doesn't support anything in terms of escape sequences. However, they do use xtermjs for the REPL console, which should support anything a normal VT100 terminal would.

> I would also have to change all of my includes to be relative to each other rather than relative to the include root

WHY THE HELL IS THIS A CONVENTION IN C++? Sorry, but HOW is this done everywhere? If you're including a file relative to the current file, shouldn't you use relative paths?

> I think the best course of action for you if you still want to pursue this course is to copy the .hpp and .cpp files from the library into your project flat. That is, without any subdirectories. Then, change all of the #includes to be flat as well.

Which file(s) should I `#include`? I'll look into it...

> That's quite the work for a school assignment. :-/

Tell me about it.

https://66-magic-squares.logandark.repl.run/
https://final.logandark.repl.run/

I had to use REPL mode for both of those because the student console couldn't support it. Obviously the "magic squares" assignment does need some optimization. The assignments were simple, but I like challenges, so I did some ridiculousness.

Before being assigned my first programming class, I had already been a self-taught programmer for about 6 years anyway. I do actually find this fun.

Speaking of ridiculousness, there is nothing I've ever created more ridiculous than my calculator. Hosted on my local machine, because no (free) online environment could ever hope to reach the power of a fully-featured IDE + CLI. https://f4b95771.ngrok.io

---

Can we continue this discussion over at #191?

**Comment by KazDragon** [comment]
> WHY THE HELL IS THIS A CONVENTION IN C++?

Is a good question.  Consider the case that you move a header file.  E.g. from detail/foo.h to parser/foo.h.  What needs to change?  The answer is: every file that includes foo.h one way or another.

If files are included relative to each other, then the ways that foo.h is included could be:
#include "lib/detail/foo.h" // (1)
#include "foo.h" 
#include "../detail/foo.h"
#include "detail/foo.h"

If files are included relative to the project's include root, then all of the includes will look like (1) above.  This means that _all_ of the includes can be updated by a global search and replace.

**Comment by KazDragon** [comment]
Closed under the category "not gonna do this one but still find it awesome that the library's useful to you."

Best of luck with the project!

**Comment by LoganDark** [comment]
I won't be able to use this anywhere but my local machine due to the Boost dependency (#191 is only part of the problem), but yeah, thanks.
